# Spatial methods
# :PROPERTIES:
# :ID:       bac12c9a-6f8a-4d1b-b8a2-041632c814f6
# :END:
# https://mail.google.com/mail/u/0/#inbox/FMfcgzGxTFWDgPhqMLGHBDfJrdBMrWXq
# [[id:4de39606-9232-4cfc-b444-f4a27e577862][Spatial ATAC-seq]]



name: spatial
channels:
  - conda-forge
  - bioconda

dependencies:
  - r-data.table
  - r-seurat
